CREATE TABLE public.weekly_servicing_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporting_week text NOT NULL,
  reporting_month text,
  msisdn text NOT NULL,
  owner_id text REFERENCES public.owners(owner_id) ON DELETE SET NULL,
  owner_name text,
  wakala_status integer,
  servicing_txns numeric NOT NULL DEFAULT 0,
  servicing_val numeric NOT NULL DEFAULT 0,
  raw jsonb NOT NULL DEFAULT '{}'::jsonb,
  uploaded_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT weekly_servicing_records_week_msisdn_key UNIQUE (reporting_week, msisdn)
);

CREATE INDEX weekly_servicing_records_week_idx ON public.weekly_servicing_records (reporting_week);
CREATE INDEX weekly_servicing_records_owner_idx ON public.weekly_servicing_records (owner_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.weekly_servicing_records TO authenticated;
GRANT ALL ON public.weekly_servicing_records TO service_role;

ALTER TABLE public.weekly_servicing_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff manage weekly servicing records"
ON public.weekly_servicing_records FOR ALL TO authenticated
USING (public.is_staff(auth.uid()))
WITH CHECK (public.is_staff(auth.uid()));

CREATE POLICY "Owners read their own weekly servicing records"
ON public.weekly_servicing_records FOR SELECT TO authenticated
USING (owner_id IS NOT NULL AND public.owns_owner(owner_id));