CREATE TABLE public.monthly_servicing_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporting_month text NOT NULL,
  msisdn text NOT NULL,
  owner_id text REFERENCES public.owners(owner_id) ON DELETE SET NULL,
  owner_name text,
  wakala_status integer,
  servicing_txns numeric NOT NULL DEFAULT 0,
  servicing_val numeric NOT NULL DEFAULT 0,
  raw jsonb NOT NULL DEFAULT '{}'::jsonb,
  uploaded_by uuid REFERENCES auth.users(id),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT monthly_servicing_records_month_msisdn_key UNIQUE (reporting_month, msisdn)
);

CREATE INDEX monthly_servicing_records_month_idx ON public.monthly_servicing_records (reporting_month);
CREATE INDEX monthly_servicing_records_owner_idx ON public.monthly_servicing_records (owner_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.monthly_servicing_records TO authenticated;
GRANT ALL ON public.monthly_servicing_records TO service_role;

ALTER TABLE public.monthly_servicing_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff manage monthly servicing records"
  ON public.monthly_servicing_records
  TO authenticated
  USING (public.is_staff(auth.uid()))
  WITH CHECK (public.is_staff(auth.uid()));

CREATE POLICY "Owners read their own monthly servicing records"
  ON public.monthly_servicing_records
  FOR SELECT
  TO authenticated
  USING (owner_id IS NOT NULL AND public.owns_owner(owner_id));